site_name: Proton UI for Roblox
theme:
    name: material
    logo: assets/logo.png
    palette:
        scheme: slate
        primary: black
    features:
        - content.code.copy
        - content.code.select

markdown_extensions:
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences