site_name: Proton
repo_url: https://github.com/ayvacs/Proton
repo_name: ayvacs/Proton

theme:
  name: material
  language: en
  logo: images/logos/white/logo.png
  favicon: images/logos/white/logo.png
  palette:
    scheme: slate
    primary: black
  font:
    text: Source Sans Pro
    code: Source Code Pro
  features:
    - navigation.instant
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

plugins:
  - git-authors
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Getting started:
    - Installation: getting-started/installation.md
    - Creating a GUI: getting-started/creating-a-gui.md
  - API Reference:
    - Proton Properties:
      - Child: api/property/child.md
      - Children: api/property/childrens.md